plugin: aws_ec2

#aws_access_key: AKIA3GLJDRATZ3RR54UM
#aws_secret_key: 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

regions:
  - ca-central-1

filters:
  instance-state-name : running
 
keyed_groups:
  - key: tags.Name
    prefix: ""
    separator: ""

hostnames:
  - private-ip-address

compose:
  ansible_host: private_ip_address
